Force python2 in shebangs
Both scripts uses Python 2 syntax (print without parentheses) and causes
build failure if python is set to python3.

Errors such as:
  File "./maketables", line 76
    print "Flags: set for %s" % self.name
                            ^
SyntaxError: Missing parentheses in call to 'print'
(...)
  File "./maketables", line 251
    print "Invalid or malformed template %s.  Aborting." % path
                                                       ^
SyntaxError: Missing parentheses in call to 'print'
(...)
  File "./maketables", line 259
    print datatype.__repr__()
                 ^
SyntaxError: invalid syntax
(...)
  File "./maketables", line 260
    print ""
           ^
SyntaxError: Missing parentheses in call to 'print'
(...)
  File "./maketables", line 267
    print "done.  Cleaning up."
                              ^
SyntaxError: Missing parentheses in call to 'print'
(...)
and so on in .py scripts.

Signed-off-by: Gaël PORTAY <gael.portay@savoirfairelinux.com>